// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQriL-Vr5sdiugsb6ttkdqA8EEn-e1ksY',
    appId: '1:805516557560:android:cc6ad7b5f667bca54c8f0d',
    messagingSenderId: '805516557560',
    projectId: 'petcare-7a6ca',
    databaseURL: 'https://petcare-7a6ca-default-rtdb.firebaseio.com',
    storageBucket: 'petcare-7a6ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpdvmmdXX0WfYKJPbnZXkMMGBn7xHZghw',
    appId: '1:805516557560:ios:0687d1476b70f20c4c8f0d',
    messagingSenderId: '805516557560',
    projectId: 'petcare-7a6ca',
    databaseURL: 'https://petcare-7a6ca-default-rtdb.firebaseio.com',
    storageBucket: 'petcare-7a6ca.appspot.com',
    iosBundleId: 'com.example.petcare',
  );
}
